
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Update system
        run: apt-get -y update
        
      - name: Set http proxy
        run: export HTTP_PROXY=http://proxy-dmz.intel.com:912
      
      - name: Set https proxy
        run: export HTTPS_PROXY=http://proxy-dmz.intel.com:912
        
      - name: SSH to node
        run: ssh ${{ secrets.USERRKE2 }}@${{ secrets.HOSTRKE2 }}
        shell: ls -la

#       - name: SSH Command
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.HOSTRKE2 }}
#           username: ${{ secrets.USERRKE2 }}
#           password: ${{ secrets.PASSRKE2 }}
#           port: ${{ secrets.PORTRKE2 }}
#           script: ls -la
