
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Update system
        run: sudo apt-get -y update
        
      - name: SSH to node
        run: |
          sshpass -p root ssh root@10.237.26.15
          whoami
