
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.3.5
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_RKE2 }}
          ssh-host: ${{ secrets.HOSTRKE2 }}

#       - name: SSH Command
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.HOSTRKE2 }}
#           username: ${{ secrets.USERRKE2 }}
#           password: ${{ secrets.PASSRKE2 }}
#           port: ${{ secrets.PORTRKE2 }}
#           script: ls -la
