
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.19
      
      - name: Update packages
        run: sudo apt-get update
        shell: bash
        
      - name: Install git
        run: |
          sudo apt-get install git -y
          git version
          git config --global user.name "marcelstancu"
        shell: bash
        
      - name: Clone validation folder
        run: git clone https://github.com/yankils/hello-world.git
        shell: bash
        
      - name: Print Home path
        run: ls -la
        shell: bash
      
      - name: Install ginkgo
        run: |
          cd validation
          go install github.com/onsi/ginkgo/v2/ginkgo
          go get github.com/onsi/gomega/...
          cd %HOME/go/bin
          ./ginkgo version
        shell: bash
